# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Chute-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RideShare
  pod 'DeviceKit'
  pod 'EasyPeasy'
  pod 'lottie-ios'
  pod 'Then'
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'
end
